version: '3'

services:
  back-end:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task6
    expose:
      - "5252"  # Expose for internal communication

  back-end-2:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: softy-pinko-back-end:task6
    expose:
      - "5252"  # Expose for internal communication

  front-end:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-pinko-front-end:task6
    expose:
      - "9000"  # Expose for internal communication
    depends_on:
      - back-end
      - back-end-2

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: softy-pinko-proxy:task6
    ports:
      - "80:80"  # Expose to the outside world
    depends_on:
      - front-end
      - back-end
      - back-end-2

networks:
  default:
    driver: bridge
